version: "3"
services:
  bot:
    build: ./bot/
      #ports:
      #  - "3000:3000"
    environment:
      MYSQL_HOST: "db"
      RIO_VERBOSE: 1
    depends_on:
      - "db"

  db:
    image: mysql:5.7 # 最新版だとbotから接続時に SSL connection error: unknown error number
    #ports:
    #  - "3306:3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_DATABASE: "test"
      BIND-ADDRESS: 0.0.0.0
    volumes: 
      - "memory:/var/lib/mysql"
    tty: true

  line:
    build: ./line/
    environment:
      VIRTUAL_HOST: "${LINE_VIRTUAL_HOST}"
      CHANNEL_ID: "${LINE_CHANNEL_ID}"
      CHANNEL_SECRET: "${LINE_CHANNEL_SECRET}"
      CHANNEL_TOKEN: "${LINE_CHANNEL_TOKEN}"
      BOT_HOST_NAME: bot
      BOT_PORT: 3000
      PORT: 3001
      
volumes:
  memory: {}

